import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthLayout, AuthProvider } from "@/components/client";
import { AppServiceProvider } from "@/lib";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppServiceProvider>
          <AuthProvider>
            <AuthLayout>{children}</AuthLayout>
          </AuthProvider>
        </AppServiceProvider>
      </body>
    </html>
  );
}
